import "./globals.css";
import { AppProvider } from "@/context/AppContext";

export const metadata = {
  title: "WhatApps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
            {children}
        </AppProvider>
      </body>
    </html>
  );
}